#!/usr/bin/env python3
"""
Config Template Generator for Ablation Study

Programmatically generates experiment config files for the cross-script transfer learning
ablation study on LipBengal and LRW-AR datasets.

Usage:
    python configs/ablations/template_generator.py --experiment S1.1 --dataset LipBengal
    python configs/ablations/template_generator.py --experiment T1.1 --dataset LRW-AR
    python configs/ablations/template_generator.py --generate-all
"""

import os
import argparse
from pathlib import Path
from typing import Dict, Any, Optional


class AblationConfigGenerator:
    """Generate ablation experiment configs from templates"""
    
    def __init__(self, base_config_dir: str = "configs"):
        self.base_config_dir = Path(base_config_dir)
        self.ablation_dir = self.base_config_dir / "ablations"
        self.ablation_dir.mkdir(exist_ok=True)
        
    def generate_lipbengal_config(
        self,
        experiment_id: str,
        script_norm: str = "phonetic",
        transfer_mode: str = "full",
        freeze_epochs: int = 5,
        encoder_lr_mult: float = 0.2,
        head_lr_mult: float = 1.0,
        target_data_fraction: float = 1.0,
        source_ckpt: Optional[str] = None,
        output_path: Optional[str] = None
    ) -> str:
        """Generate LipBengal ablation config
        
        Args:
            experiment_id: Experiment ID (e.g., S1.1, T1.1)
            script_norm: Script normalization type (raw, phonetic, simple, mixed)
            transfer_mode: Transfer learning mode (scratch, full, frontend, backend)
            freeze_epochs: Number of epochs to freeze encoder (0 = no freeze)
            encoder_lr_mult: Learning rate multiplier for encoder
            head_lr_mult: Learning rate multiplier for head
            target_data_fraction: Fraction of target dataset to use (0.1-1.0)
            source_ckpt: Path to source checkpoint for transfer learning
            output_path: Output config file path
        """
        
        if output_path is None:
            safe_id = experiment_id.replace(".", "_")
            output_path = self.base_config_dir / "LipBengal" / "AV" / "ablations" / f"{safe_id}.py"
        
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Determine transfer loading logic based on mode
        if transfer_mode == "scratch":
            transfer_load_code = "# No transfer learning - training from scratch\n"
        elif transfer_mode == "full":
            transfer_load_code = self._generate_full_transfer_code(source_ckpt)
        elif transfer_mode == "frontend":
            transfer_load_code = self._generate_frontend_transfer_code(source_ckpt)
        elif transfer_mode == "backend":
            transfer_load_code = self._generate_backend_transfer_code(source_ckpt)
        else:
            raise ValueError(f"Unknown transfer mode: {transfer_mode}")
        
        # Generate script normalization configuration
        script_norm_config = self._generate_script_norm_config(script_norm)
        
        config_content = f'''"""
Ablation Config: {experiment_id} - LipBengal
Generated by template_generator.py

Experiment Configuration:
- Script Normalization: {script_norm}
- Transfer Mode: {transfer_mode}
- Freeze Epochs: {freeze_epochs}
- Encoder LR Mult: {encoder_lr_mult}
- Head LR Mult: {head_lr_mult}
- Data Fraction: {target_data_fraction}
"""

import sys
sys.path.append("../../")

import os
import torch
import torch.nn as nn
import nnet
from nnet import transforms as vtf
from nnet import optimizers as _optim
from nnet import schedulers as _schedulers

# Environment variable overrides
SCRIPT_NORMALIZATION_TYPE = os.environ.get("SCRIPT_NORMALIZATION_TYPE", "{script_norm}")
TRANSFER_MODE = os.environ.get("TRANSFER_MODE", "{transfer_mode}")
FREEZE_ENCODER_EPOCHS = int(os.environ.get("FREEZE_ENCODER_EPOCHS", {freeze_epochs}))
ENCODER_LR_MULT = float(os.environ.get("ENCODER_LR_MULT", {encoder_lr_mult}))
HEAD_LR_MULT = float(os.environ.get("HEAD_LR_MULT", {head_lr_mult}))
TARGET_DATA_FRACTION = float(os.environ.get("TARGET_DATA_FRACTION", {target_data_fraction}))

# ---------------------------------------------------------------------------
# Data & Transforms
# ---------------------------------------------------------------------------

crop_size = (88, 88)
train_video_transform = nn.Sequential(
    vtf.RandomTemporalShift(max_shift=2),
    vtf.RandomCropVideo(crop_size),
    vtf.RandomHorizontalFlipVideo(p=0.5),
)
val_video_transform = vtf.CenterCropVideo(crop_size)

collate_fn = nnet.CollateFn(inputs_params=[{{"axis": 0}}], targets_params=[{{"axis": 2}}])

{script_norm_config}

training_dataset = nnet.datasets.LipBengal(
    batch_size=32,
    collate_fn=collate_fn,
    mode="train",
    video_transform=train_video_transform,
    num_frames=None,
    fixed_frames=29,
    indices_path="datasets/LipBengal/indices/train.pt",
    subset_fraction=TARGET_DATA_FRACTION,
    subset_seed=42,
    prepared_only=True,
    label_format="{script_norm}",  # Script normalization type
)

evaluation_dataset = nnet.datasets.LipBengal(
    batch_size=64,
    collate_fn=collate_fn,
    mode="val",
    video_transform=val_video_transform,
    fixed_frames=29,
    indices_path="datasets/LipBengal/indices/val.pt",
    subset_fraction=1.0,
    subset_seed=42,
    prepared_only=True,
    label_format="{script_norm}",  # Script normalization type
)

# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

vocab_size = training_dataset.num_classes
model = nnet.VisualEfficientConformerCE(vocab_size=vocab_size)

# ---------------------------------------------------------------------------
# Optimizer with differential LR scaling
# ---------------------------------------------------------------------------

def build_param_groups_with_scaling(model: torch.nn.Module, encoder_lr_scale: float, head_lr_scale: float):
    decay_modules = (torch.nn.Linear, torch.nn.Conv1d, torch.nn.Conv2d, torch.nn.Conv3d)
    no_decay_modules = (torch.nn.LayerNorm, torch.nn.Embedding, torch.nn.BatchNorm1d, torch.nn.BatchNorm2d, torch.nn.BatchNorm3d)
    decay_params = ("weight",)
    no_decay_params = ("bias",)

    enc_decay, enc_no_decay, head_decay, head_no_decay = [], [], [], []
    for module_name, module in model.named_modules():
        for param_name, param in module.named_parameters(recurse=False):
            full_name = f"{{module_name}}.{{param_name}}" if module_name else param_name
            target_list_decay = enc_decay if full_name.startswith("encoder.") else head_decay
            target_list_no_decay = enc_no_decay if full_name.startswith("encoder.") else head_no_decay
            
            placed = False
            for nd in no_decay_params:
                if param_name.endswith(nd):
                    target_list_no_decay.append(param)
                    placed = True
                    break
            if placed:
                continue
            for dp in decay_params:
                if param_name.endswith(dp) and isinstance(module, decay_modules):
                    target_list_decay.append(param)
                    placed = True
                    break
                if param_name.endswith(dp) and isinstance(module, no_decay_modules):
                    target_list_no_decay.append(param)
                    placed = True
                    break
            if not placed:
                target_list_no_decay.append(param)

    return [
        {{"params": enc_decay, "weight_decay": 0.05, "lr_scale": encoder_lr_scale}},
        {{"params": enc_no_decay, "weight_decay": 0.0,  "lr_scale": encoder_lr_scale}},
        {{"params": head_decay, "weight_decay": 0.05, "lr_scale": head_lr_scale}},
        {{"params": head_no_decay, "weight_decay": 0.0,  "lr_scale": head_lr_scale}},
    ]


class MultiScaleAdamW(_optim.AdamW):
    def step(self, closure=None):
        base_lr = self.scheduler.step()
        for group in self.param_groups:
            scale = group.get("lr_scale", 1.0)
            group['lr'] = base_lr * scale
        return super(_optim.AdamW, self).step(closure)


_words = training_dataset.classes
_label_to_word = nnet.ClassLabelToWordDecoder(_words)

transfer_scheduler = _schedulers.CosineAnnealingScheduler(
    warmup_steps=100,
    val_max=5e-5,
    val_min=5e-6,
    end_step=200000,
)

param_groups = build_param_groups_with_scaling(model, ENCODER_LR_MULT, HEAD_LR_MULT)
optimizer = MultiScaleAdamW(
    params=param_groups,
    lr=transfer_scheduler,
    betas=(0.9, 0.98),
    eps=1e-8,
)

model.compile(
    losses=nnet.SoftmaxCrossEntropy(label_smoothing=0.1),
    metrics={{
        "output": [
            nnet.CategoricalAccuracy(),
            nnet.WordErrorRate(),
            nnet.CharacterErrorRate(),
        ]
    }},
    decoders={{
        "output": [
            None,
            _label_to_word,
            _label_to_word,
        ]
    }},
    optimizer=optimizer,
    grad_max_norm=1.0,
    ema_tau=0.999,
)

# ---------------------------------------------------------------------------
# Freezing & Unfreezing Logic
# ---------------------------------------------------------------------------

def _freeze_backbone_keep_head(m):
    head_params = set(id(p) for p in m.encoder.head.parameters()) if hasattr(m.encoder, 'head') else set()
    frozen, kept = 0, 0
    for p in m.encoder.parameters():
        if id(p) in head_params:
            p.requires_grad = True
            kept += 1
        else:
            p.requires_grad = False
            frozen += 1
    return frozen, kept

if FREEZE_ENCODER_EPOCHS > 0 and TRANSFER_MODE != "scratch":
    frozen, kept = _freeze_backbone_keep_head(model)
    print(f"[Ablation {experiment_id}] Frozen: {{frozen}}, Trainable: {{kept}} for {{FREEZE_ENCODER_EPOCHS}} epochs")

_orig_on_epoch_end = model.on_epoch_end

def _transfer_on_epoch_end(evaluate, save, log_figure, callback_path, epoch, *a, **kw):
    res = _orig_on_epoch_end(evaluate, save, log_figure, callback_path, epoch, *a, **kw)
    if epoch == FREEZE_ENCODER_EPOCHS and TRANSFER_MODE != "scratch":
        unfroze = 0
        for p in model.encoder.parameters():
            if not p.requires_grad:
                p.requires_grad = True
                unfroze += 1
        if unfroze:
            print(f"[Ablation {experiment_id}] Unfroze {{unfroze}} params at epoch {{epoch}}")
    return res

model.on_epoch_end = _transfer_on_epoch_end

# ---------------------------------------------------------------------------
# Transfer Learning Weight Loading
# ---------------------------------------------------------------------------

{transfer_load_code}

# ---------------------------------------------------------------------------
# Training Configuration
# ---------------------------------------------------------------------------

epochs = 600
precision = torch.float16
accumulated_steps = 1
eval_training = False
callback_path = "callbacks/LipBengal/AV/ablations/{experiment_id}"
verbose_eval = 1
eval_period_epoch = 1
saving_period_epoch = 1

try:
    total_steps = epochs * len(training_dataset)
    model.optimizer.scheduler.end_step = total_steps
except Exception:
    pass
'''
        
        with open(output_path, 'w') as f:
            f.write(config_content)
        
        print(f"Generated config: {output_path}")
        return str(output_path)
    
    def generate_lrwar_config(
        self,
        experiment_id: str,
        script_norm: str = "phonetic",
        transfer_mode: str = "full",
        freeze_epochs: int = 5,
        encoder_lr_mult: float = 0.2,
        head_lr_mult: float = 1.0,
        target_data_fraction: float = 1.0,
        source_ckpt: Optional[str] = None,
        output_path: Optional[str] = None
    ) -> str:
        """Generate LRW-AR ablation config (similar structure to LipBengal)"""
        
        if output_path is None:
            safe_id = experiment_id.replace(".", "_")
            output_path = self.base_config_dir / "LRW-AR" / "AV" / "ablations" / f"{safe_id}.py"
        
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Similar structure but for LRW-AR dataset
        if transfer_mode == "scratch":
            transfer_load_code = "# No transfer learning - training from scratch\n"
        elif transfer_mode == "full":
            transfer_load_code = self._generate_full_transfer_code(source_ckpt)
        elif transfer_mode == "frontend":
            transfer_load_code = self._generate_frontend_transfer_code(source_ckpt)
        elif transfer_mode == "backend":
            transfer_load_code = self._generate_backend_transfer_code(source_ckpt)
        else:
            raise ValueError(f"Unknown transfer mode: {transfer_mode}")
        
        script_norm_config = self._generate_script_norm_config(script_norm)
        
        config_content = f'''"""
Ablation Config: {experiment_id} - LRW-AR
Generated by template_generator.py

Experiment Configuration:
- Script Normalization: {script_norm}
- Transfer Mode: {transfer_mode}
- Freeze Epochs: {freeze_epochs}
- Encoder LR Mult: {encoder_lr_mult}
- Head LR Mult: {head_lr_mult}
- Data Fraction: {target_data_fraction}
"""

import sys
sys.path.append("../../")

import os
import torch
import torch.nn as nn
import nnet
from nnet import transforms as vtf
from nnet import optimizers as _optim
from nnet import schedulers as _schedulers

# Environment variable overrides
SCRIPT_NORMALIZATION_TYPE = os.environ.get("SCRIPT_NORMALIZATION_TYPE", "{script_norm}")
TRANSFER_MODE = os.environ.get("TRANSFER_MODE", "{transfer_mode}")
FREEZE_ENCODER_EPOCHS = int(os.environ.get("FREEZE_ENCODER_EPOCHS", {freeze_epochs}))
ENCODER_LR_MULT = float(os.environ.get("ENCODER_LR_MULT", {encoder_lr_mult}))
HEAD_LR_MULT = float(os.environ.get("HEAD_LR_MULT", {head_lr_mult}))
TARGET_DATA_FRACTION = float(os.environ.get("TARGET_DATA_FRACTION", {target_data_fraction}))

# ---------------------------------------------------------------------------
# Data & Transforms
# ---------------------------------------------------------------------------

crop_size = (88, 88)
center_crop = (96, 96)

train_video_transform = nn.Sequential(
    vtf.RandomTemporalShift(max_shift=2),
    vtf.RandomCropVideo(crop_size),
    vtf.RandomHorizontalFlipVideo(p=0.5),
)

val_video_transform = vtf.CenterCropVideo(crop_size)

collate_fn = nnet.CollateFn(inputs_params=[{{"axis": 0}}], targets_params=[{{"axis": 2}}])

{script_norm_config}

training_dataset = nnet.datasets.LRWAR(
    batch_size=32,
    collate_fn=collate_fn,
    mode="train",
    video_transform=train_video_transform,
    center_crop_size=center_crop,
    fixed_frames=29,
    load_audio=False,
    indices_path="datasets/LRW-AR/indices/train.pt",
    prepared_only=True,
    use_arabish=True,  # Always use transliteration for LRW-AR
    subset_fraction=TARGET_DATA_FRACTION,
    subset_seed=42,
)

evaluation_dataset = nnet.datasets.LRWAR(
    batch_size=64,
    collate_fn=collate_fn,
    mode="val",
    video_transform=val_video_transform,
    center_crop_size=center_crop,
    fixed_frames=29,
    load_audio=False,
    indices_path="datasets/LRW-AR/indices/val.pt",
    prepared_only=True,
    use_arabish=True,
    subset_fraction=1.0,
    subset_seed=42,
)

# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

vocab_size = training_dataset.num_classes
model = nnet.VisualEfficientConformerCE(vocab_size=vocab_size)

# ---------------------------------------------------------------------------
# Optimizer with differential LR scaling
# ---------------------------------------------------------------------------

def build_param_groups_with_scaling(model: torch.nn.Module, encoder_lr_scale: float, head_lr_scale: float):
    decay_modules = (torch.nn.Linear, torch.nn.Conv1d, torch.nn.Conv2d, torch.nn.Conv3d)
    no_decay_modules = (torch.nn.LayerNorm, torch.nn.Embedding, torch.nn.BatchNorm1d, torch.nn.BatchNorm2d, torch.nn.BatchNorm3d)
    decay_params = ("weight",)
    no_decay_params = ("bias",)

    enc_decay, enc_no_decay, head_decay, head_no_decay = [], [], [], []
    for module_name, module in model.named_modules():
        for param_name, param in module.named_parameters(recurse=False):
            full_name = f"{{module_name}}.{{param_name}}" if module_name else param_name
            is_encoder = full_name.startswith("encoder.")
            target_decay = enc_decay if is_encoder else head_decay
            target_no_decay = enc_no_decay if is_encoder else head_no_decay
            
            placed = False
            for nd in no_decay_params:
                if param_name.endswith(nd):
                    target_no_decay.append(param)
                    placed = True
                    break
            if placed:
                continue
            for dp in decay_params:
                if param_name.endswith(dp) and isinstance(module, decay_modules):
                    target_decay.append(param)
                    placed = True
                    break
                if param_name.endswith(dp) and isinstance(module, no_decay_modules):
                    target_no_decay.append(param)
                    placed = True
                    break
            if not placed:
                target_no_decay.append(param)

    return [
        {{"params": enc_decay, "weight_decay": 0.05, "lr_scale": encoder_lr_scale}},
        {{"params": enc_no_decay, "weight_decay": 0.0,  "lr_scale": encoder_lr_scale}},
        {{"params": head_decay, "weight_decay": 0.05, "lr_scale": head_lr_scale}},
        {{"params": head_no_decay, "weight_decay": 0.0,  "lr_scale": head_lr_scale}},
    ]


class MultiScaleAdamW(_optim.AdamW):
    def step(self, closure=None):
        base_lr = self.scheduler.step()
        for group in self.param_groups:
            scale = group.get("lr_scale", 1.0)
            group['lr'] = base_lr * scale
        return super(_optim.AdamW, self).step(closure)


_words = training_dataset.classes
_label_to_word = nnet.ClassLabelToWordDecoder(_words)

transfer_scheduler = _schedulers.CosineAnnealingScheduler(
    warmup_steps=100,
    val_max=5e-5,
    val_min=5e-6,
    end_step=200000,
)

param_groups = build_param_groups_with_scaling(model, ENCODER_LR_MULT, HEAD_LR_MULT)
optimizer = MultiScaleAdamW(
    params=param_groups,
    lr=transfer_scheduler,
    betas=(0.9, 0.98),
    eps=1e-8,
)

model.compile(
    losses=nnet.SoftmaxCrossEntropy(label_smoothing=0.1),
    metrics={{
        "output": [
            nnet.CategoricalAccuracy(),
            nnet.WordErrorRate(),
            nnet.CharacterErrorRate(),
        ]
    }},
    decoders={{
        "output": [
            None,
            _label_to_word,
            _label_to_word,
        ]
    }},
    optimizer=optimizer,
    grad_max_norm=1.0,
    ema_tau=0.999,
)

# ---------------------------------------------------------------------------
# Freezing & Unfreezing Logic
# ---------------------------------------------------------------------------

def _freeze_backbone_keep_head(m):
    head_params = set(id(p) for p in getattr(m.encoder, 'head').parameters()) if hasattr(m.encoder, 'head') else set()
    frozen = kept = 0
    for p in m.encoder.parameters():
        if id(p) in head_params:
            p.requires_grad = True
            kept += 1
        else:
            p.requires_grad = False
            frozen += 1
    return frozen, kept

if FREEZE_ENCODER_EPOCHS > 0 and TRANSFER_MODE != "scratch":
    frozen, kept = _freeze_backbone_keep_head(model)
    print(f"[Ablation {experiment_id}] Frozen: {{frozen}}, Trainable: {{kept}} for {{FREEZE_ENCODER_EPOCHS}} epochs")

_orig_on_epoch_end = model.on_epoch_end

def _transfer_on_epoch_end(evaluate, save, log_figure, callback_path, epoch, *a, **kw):
    res = _orig_on_epoch_end(evaluate, save, log_figure, callback_path, epoch, *a, **kw)
    if epoch == FREEZE_ENCODER_EPOCHS and TRANSFER_MODE != "scratch":
        unfroze = 0
        for p in model.encoder.parameters():
            if not p.requires_grad:
                p.requires_grad = True
                unfroze += 1
        if unfroze:
            print(f"[Ablation {experiment_id}] Unfroze {{unfroze}} params at epoch {{epoch}}")
    return res

model.on_epoch_end = _transfer_on_epoch_end

# ---------------------------------------------------------------------------
# Transfer Learning Weight Loading
# ---------------------------------------------------------------------------

{transfer_load_code}

# ---------------------------------------------------------------------------
# Training Configuration
# ---------------------------------------------------------------------------

epochs = 600
precision = torch.float16
accumulated_steps = 1
eval_training = False
callback_path = "callbacks/LRW-AR/AV/ablations/{experiment_id}"
verbose_eval = 1
eval_period_epoch = 1
saving_period_epoch = 1

try:
    total_steps = epochs * len(training_dataset)
    model.optimizer.scheduler.end_step = total_steps
except Exception:
    pass
'''
        
        with open(output_path, 'w') as f:
            f.write(config_content)
        
        print(f"Generated config: {output_path}")
        return str(output_path)
    
    def _generate_script_norm_config(self, script_norm: str) -> str:
        """Generate script normalization configuration comments"""
        if script_norm == "raw":
            return "# Script Normalization: RAW (using original Bengali/Arabic script - expected to fail)"
        elif script_norm == "phonetic":
            return "# Script Normalization: PHONETIC (IPA-based romanization - your approach)"
        elif script_norm == "simple":
            return "# Script Normalization: SIMPLE (character-level transliteration)"
        elif script_norm == "mixed":
            return "# Script Normalization: MIXED (preserve script + romanization auxiliary)"
        else:
            return f"# Script Normalization: {script_norm}"
    
    def _generate_full_transfer_code(self, source_ckpt: Optional[str]) -> str:
        """Generate full transfer learning code"""
        if source_ckpt is None:
            source_ckpt = "callbacks/LRS23/VO/EffConfInterCTC/checkpoints_swa-equal-90-100.ckpt"
        
        return f'''
source_ckpt = os.environ.get("SOURCE_CKPT", "{source_ckpt}")
try:
    ck = torch.load(source_ckpt, map_location="cpu")
    state = ck.get("model_state_dict", {{}})
    msd = model.state_dict()
    loadable = {{}}
    for k, v in state.items():
        if (k.startswith("encoder.front_end") or k.startswith("encoder.back_end")) and "head" not in k:
            if k in msd and getattr(v, 'shape', None) == getattr(msd[k], 'shape', None):
                loadable[k] = v
    if loadable:
        msd.update(loadable)
        model.load_state_dict(msd, strict=False)
        print(f"[Transfer] Loaded {{len(loadable)}} encoder tensors from {{source_ckpt}}")
except Exception as e:
    print(f"[Transfer] Load failed: {{e}}")
'''
    
    def _generate_frontend_transfer_code(self, source_ckpt: Optional[str]) -> str:
        """Generate frontend-only transfer code"""
        if source_ckpt is None:
            source_ckpt = "callbacks/LRS23/VO/EffConfInterCTC/checkpoints_swa-equal-90-100.ckpt"
        
        return f'''
source_ckpt = os.environ.get("SOURCE_CKPT", "{source_ckpt}")
try:
    ck = torch.load(source_ckpt, map_location="cpu")
    state = ck.get("model_state_dict", {{}})
    msd = model.state_dict()
    loadable = {{}}
    for k, v in state.items():
        if k.startswith("encoder.front_end") and "head" not in k:
            if k in msd and getattr(v, 'shape', None) == getattr(msd[k], 'shape', None):
                loadable[k] = v
    if loadable:
        msd.update(loadable)
        model.load_state_dict(msd, strict=False)
        print(f"[Transfer Frontend Only] Loaded {{len(loadable)}} frontend tensors from {{source_ckpt}}")
except Exception as e:
    print(f"[Transfer] Frontend load failed: {{e}}")
'''
    
    def _generate_backend_transfer_code(self, source_ckpt: Optional[str]) -> str:
        """Generate backend-only transfer code"""
        if source_ckpt is None:
            source_ckpt = "callbacks/LRS23/VO/EffConfInterCTC/checkpoints_swa-equal-90-100.ckpt"
        
        return f'''
source_ckpt = os.environ.get("SOURCE_CKPT", "{source_ckpt}")
try:
    ck = torch.load(source_ckpt, map_location="cpu")
    state = ck.get("model_state_dict", {{}})
    msd = model.state_dict()
    loadable = {{}}
    for k, v in state.items():
        if k.startswith("encoder.back_end") and "head" not in k:
            if k in msd and getattr(v, 'shape', None) == getattr(msd[k], 'shape', None):
                loadable[k] = v
    if loadable:
        msd.update(loadable)
        model.load_state_dict(msd, strict=False)
        print(f"[Transfer Backend Only] Loaded {{len(loadable)}} backend tensors from {{source_ckpt}}")
except Exception as e:
    print(f"[Transfer] Backend load failed: {{e}}")
'''
    
    def generate_phase1_configs(self):
        """Generate all Phase 1 (Script Normalization) configs"""
        print("\n=== Generating Phase 1 Configs ===")
        configs = []
        
        # S1: Script normalization variants
        # Match experiment IDs from ablation_env.py
        for dataset in ["LipBengal", "LRW-AR"]:
            gen_func = self.generate_lipbengal_config if dataset == "LipBengal" else self.generate_lrwar_config
            
            # S1_raw: Raw script (baseline - expected to fail)
            configs.append(gen_func(
                "S1_raw",
                script_norm="raw",
                transfer_mode="full",
                freeze_epochs=5
            ))
            
            # S1_phonetic: Phonetic romanization (your approach - baseline)
            configs.append(gen_func(
                "S1_phonetic",
                script_norm="phonetic",
                transfer_mode="full",
                freeze_epochs=5
            ))
            
            # S1_simple: Simple transliteration
            configs.append(gen_func(
                "S1_simple",
                script_norm="simple",
                transfer_mode="full",
                freeze_epochs=5
            ))
            
            # S1_mixed: Mixed approach
            configs.append(gen_func(
                "S1_mixed",
                script_norm="mixed",
                transfer_mode="full",
                freeze_epochs=5
            ))
        
        return configs
    
    def generate_phase2_configs(self):
        """Generate all Phase 2 (Transfer Learning Strategy) configs"""
        print("\n=== Generating Phase 2 Configs ===")
        configs = []
        
        # T1: Transfer Learning Effectiveness
        for transfer_mode in ["scratch", "frontend", "backend"]:  # "full" is baseline
            for dataset in ["LipBengal", "LRW-AR"]:
                exp_id = f"T1_{transfer_mode}"
                if dataset == "LipBengal":
                    configs.append(self.generate_lipbengal_config(
                        exp_id,
                        script_norm="phonetic",
                        transfer_mode=transfer_mode,
                        freeze_epochs=5 if transfer_mode != "scratch" else 0
                    ))
                else:
                    configs.append(self.generate_lrwar_config(
                        exp_id,
                        script_norm="phonetic",
                        transfer_mode=transfer_mode,
                        freeze_epochs=5 if transfer_mode != "scratch" else 0
                    ))
        
        # T2: Freezing Strategy
        for freeze_epochs in [0, 3, 10]:  # 5 is baseline
            for dataset in ["LipBengal", "LRW-AR"]:
                exp_id = f"T2_freeze_{freeze_epochs}ep"
                if dataset == "LipBengal":
                    configs.append(self.generate_lipbengal_config(
                        exp_id,
                        script_norm="phonetic",
                        transfer_mode="full",
                        freeze_epochs=freeze_epochs
                    ))
                else:
                    configs.append(self.generate_lrwar_config(
                        exp_id,
                        script_norm="phonetic",
                        transfer_mode="full",
                        freeze_epochs=freeze_epochs
                    ))
        
        # T3: Differential Learning Rates
        for encoder_lr in [1.0, 0.1, 0.5]:  # 0.2 is baseline
            for dataset in ["LipBengal", "LRW-AR"]:
                exp_id = f"T3_lr_{str(encoder_lr).replace('.', '_')}"
                if dataset == "LipBengal":
                    configs.append(self.generate_lipbengal_config(
                        exp_id,
                        script_norm="phonetic",
                        transfer_mode="full",
                        freeze_epochs=5,
                        encoder_lr_mult=encoder_lr
                    ))
                else:
                    configs.append(self.generate_lrwar_config(
                        exp_id,
                        script_norm="phonetic",
                        transfer_mode="full",
                        freeze_epochs=5,
                        encoder_lr_mult=encoder_lr
                    ))
        
        return configs
    
    def generate_phase3_configs(self):
        """Generate all Phase 3 (Dataset Analysis) configs"""
        print("\n=== Generating Phase 3 Configs ===")
        configs = []
        
        # D1: Target Dataset Size
        for fraction in [0.1, 0.25, 0.5, 0.75]:  # 1.0 is baseline
            for dataset in ["LipBengal", "LRW-AR"]:
                exp_id = f"D1_data_{int(fraction*100)}pct"
                if dataset == "LipBengal":
                    configs.append(self.generate_lipbengal_config(
                        exp_id,
                        script_norm="phonetic",
                        transfer_mode="full",
                        freeze_epochs=5,
                        target_data_fraction=fraction
                    ))
                else:
                    configs.append(self.generate_lrwar_config(
                        exp_id,
                        script_norm="phonetic",
                        transfer_mode="full",
                        freeze_epochs=5,
                        target_data_fraction=fraction
                    ))
        
        return configs
    
    def generate_all_configs(self):
        """Generate all ablation configs"""
        all_configs = []
        all_configs.extend(self.generate_phase1_configs())
        all_configs.extend(self.generate_phase2_configs())
        all_configs.extend(self.generate_phase3_configs())
        print(f"\n=== Generated {len(all_configs)} config files ===")
        return all_configs


def main():
    parser = argparse.ArgumentParser(description="Generate ablation study config files")
    parser.add_argument("--experiment", type=str, help="Experiment ID (e.g., S1.1, T1.1)")
    parser.add_argument("--dataset", type=str, choices=["LipBengal", "LRW-AR"], help="Dataset")
    parser.add_argument("--generate-all", action="store_true", help="Generate all configs")
    parser.add_argument("--phase", type=int, choices=[1, 2, 3], help="Generate configs for specific phase")
    
    args = parser.parse_args()
    
    generator = AblationConfigGenerator()
    
    if args.generate_all:
        generator.generate_all_configs()
    elif args.phase:
        if args.phase == 1:
            generator.generate_phase1_configs()
        elif args.phase == 2:
            generator.generate_phase2_configs()
        elif args.phase == 3:
            generator.generate_phase3_configs()
    elif args.experiment and args.dataset:
        # Generate single config
        print(f"Generating config for {args.experiment} on {args.dataset}")
        # Add more custom generation logic here
    else:
        parser.print_help()


if __name__ == "__main__":
    main()

