#!/usr/bin/env python3
"""
Create a minimal, self-contained folder to train on LRS2 and LipBengal using this repo's code.

It copies the essentials (main.py, functions.py, nnet package, and configs) into export/minimal_avec,
and writes a small README and requirements.txt so it can run on another machine with the datasets present.

Usage:
  python scripts/export_minimal.py [--dest export/minimal_avec]
"""
from __future__ import annotations

import argparse
import os
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def copy_file(src: Path, dst: Path):
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def copy_tree(src: Path, dst: Path, ignore: shutil.IgnorePattern | None = None):
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=ignore)


def write_text(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dest", default=str(ROOT / "export" / "minimal_avec"))
    args = ap.parse_args()

    dest = Path(args.dest)
    dest.mkdir(parents=True, exist_ok=True)

    # 1) Core runner and utilities
    copy_file(ROOT / "main.py", dest / "main.py")
    copy_file(ROOT / "functions.py", dest / "functions.py")

    # 2) Minimal configs (LRS2 + LipBengal Visual CE)
    copy_file(ROOT / "configs" / "LRS2" / "AV" / "EffConfInterCTC.py", dest / "configs" / "LRS2" / "AV" / "EffConfInterCTC.py")
    copy_file(ROOT / "configs" / "LipBengal" / "AV" / "VisualCE.py", dest / "configs" / "LipBengal" / "AV" / "VisualCE.py")
    copy_file(ROOT / "configs" / "LipBengal" / "AV" / "VisualCE_full.py", dest / "configs" / "LipBengal" / "AV" / "VisualCE_full.py")

    # 3) Datasets helper: LipBengal prepare script (optional, only needed to build indices/prepared crops)
    src_prepare = ROOT / "scripts" / "prepare_lipbengal.py"
    if src_prepare.exists():
        copy_file(src_prepare, dest / "scripts" / "prepare_lipbengal.py")

    # 4) Media assets (mean-face landmarks) used by LRS2-style lip crop (optional)
    mf = ROOT / "media" / "20words_mean_face.npy"
    if mf.exists():
        copy_file(mf, dest / "media" / "20words_mean_face.npy")

    # 5) Copy the whole nnet package (safest to keep all internal dependencies intact)
    nnet_src = ROOT / "nnet"
    nnet_dst = dest / "nnet"
    # Prune big optional submodules if they exist under nnet (none expected here)
    copy_tree(nnet_src, nnet_dst)

    # 6) Write a minimal requirements.txt
    req = """
torch>=2.1
torchvision>=0.16
torchaudio>=2.1
numpy>=1.23
tqdm>=4.66
sentencepiece>=0.1.99
opencv-python>=4.7  # optional: only needed for faster preprocessing
gdown>=4.7          # optional: for LRS downloads in helper scripts
requests>=2.31      # optional: for LRS downloads in helper scripts
""".strip() + "\n"
    write_text(dest / "requirements.txt", req)

    # 7) Write a concise README
    readme = f"""
# Minimal AVEC (LRS2 + LipBengal) training

This folder was generated by scripts/export_minimal.py from the full repo. It contains only what's needed to train:
- Visual-only CE model on LipBengal
- AV InterCTC model on LRS2 (expects data prepared in the original LRS2 layout)

## Layout
- main.py, functions.py: entrypoint and loader
- nnet/: model, training loop, datasets, transforms, metrics
- configs/: ready-to-run configs
- scripts/prepare_lipbengal.py: build indices and optional prepared mouth crops
- media/20words_mean_face.npy: mean face landmarks for alignment (optional)

## Setup
1) Create a Python environment and install deps:
   - pip install -r requirements.txt

2) Place datasets next to this folder using the following structure:
   - datasets/LipBengal/... (your speaker/word frames and indices)
   - datasets/LRS2/... (mvlrs_v1 with mp4/flac/txt and optionally LRS2_landmarks)

## LipBengal: prepare and train (visual-only)
Optional (to build indices and aligned mouth crops):
   - python scripts/prepare_lipbengal.py --root datasets/LipBengal --split_mode by_clip --align --landmarks mp --drop_on_fail

Then train (subset config) or full config:
   - python main.py -c configs/LipBengal/AV/VisualCE.py -m training -j 2
   - python main.py -c configs/LipBengal/AV/VisualCE_full.py -m training -j 2

Resume last checkpoint:
   - python main.py -c configs/LipBengal/AV/VisualCE_full.py -m training --load_last -j 2

## LRS2: train AV InterCTC (greedy decode)
Ensure LRS2 is downloaded and prepared (txt/mp4/flac in datasets/LRS2/mvlrs_v1 and file lists in datasets/LRS2/...).
Run:
   - python main.py -c configs/LRS2/AV/EffConfInterCTC.py -m training -j 2

Notes:
- For LRS2, the config uses greedy decoding by default (no LM). Adjust batch size to your GPU memory.
- For LipBengal, the configs expect prepared indices in datasets/LipBengal/indices/{{train,val,test}}.pt.
"""
    write_text(dest / "README.md", readme)

    print(f"Exported minimal training folder to: {dest}")


if __name__ == "__main__":
    main()
